#!/usr/local/bin/php
<?php

/* Usage: set-pfsense-password <user_name> <password>
 *
 * Changes both the system password and the stored config.xml password for user
 */

require_once('config.inc');
require_once('auth.inc');

function generateRandomPassword($length = 15) {

	/* get some random bytes. use them as offsets into the space of
	   printable ascii characters. 32-126 is the printable characters.
	   Omit 32 itself since it might be confusing if there is a space
	   in the password.
	*/

	$range_size = 126 - 33 + 1;
	$random_bytes = str_split(openssl_random_pseudo_bytes($length));
	
	for ($i = 0; $i < $length; $i++) {

		$offset = ord($random_bytes[$i]) % $range_size;
		$password .= chr(33 + $offset);

	}

	return $password;
}

if (!isset($config['system']['user']) || !is_array($config['system']['user']))
	$config['system']['user'] = array();

$a_user = &$config['system']['user'];
$user_config = array();
$groups = array();

if (empty($argv[1])) {
	exit(1);
}

/* if the user doesn't exist, exit */
$existing_id = -1;
foreach ($a_user as $userid => $userent) {
	if ($argv[1] == $userent['name']) {
		$user_config = &$userent;
		$existing_id = $userid;
		break;
	}
}
if ($argv[1] == "root") {
	$existing_id = 0;
	$user_config = array(
		'uid' => 0,
		'name' => 'root'
	);
}

if ($existing_id == -1) {
	exit(1);
}

if ($user_config['uid'] == 0) {
	$user_home = "/root";
} else {
	$user_home = "/home/" . $user_config['name'];
}

/* if no password was given, generate a random one and save it to a file
 * in the users home directory for use with the web GUI.
 */
if (empty($argv[2])) {
	$pw = generateRandomPassword();
	$pwfile = "$user_home/random_passwd.txt";
	file_put_contents($pwfile,
	    "The random password generated for this user is '$pw'\n");
	chown($pwfile, $user_config['name']);
	chmod($pwfile, 0600);
} else {
	$pw = $argv[2];
}

/* update the system password (master.passwd) */
local_user_set_password($user_config, $pw);
local_user_set($user_config);

/* update the config.xml password */
if ($user_config['name'] != 'root') {
	$a_user[$existing_id] = $user_config;
	write_config();
}

exit(0);

?>
