# $FreeBSD$

MASTERDIR=	${.CURDIR}/../pfSense-pkg-zabbix-proxy

PORTNAME=	pfSense-pkg-zabbix-proxy4

CONFLICTS=	pfSense-pkg-zabbix-proxy \
		pfSense-pkg-zabbix-proxy44 \
		pfSense-pkg-zabbix-proxy5 \
		pfSense-pkg-zabbix-proxy54 \
		pfSense-pkg-zabbix-proxy6

RUN_DEPENDS=	zabbix_proxy:net-mgmt/zabbix4-proxy

ZABBIXINTERNALNAME=	zabbix-proxy4
ZABBIXTITLE=	Zabbix Proxy 4.0
ZABBIXVERSION=	40

.include "${MASTERDIR}/Makefile"
