# $FreeBSD$

MASTERDIR=	${.CURDIR}/../pfSense-pkg-zabbix-proxy

PORTNAME=	pfSense-pkg-zabbix-proxy74

CONFLICTS=	pfSense-pkg-zabbix-proxy
CONFLICTS+=	pfSense-pkg-zabbix-proxy6
CONFLICTS+=	pfSense-pkg-zabbix-proxy7

RUN_DEPENDS=	zabbix_proxy:net-mgmt/zabbix74-proxy

ZABBIXINTERNALNAME=	zabbix-proxy74
ZABBIXTITLE=	Zabbix Proxy 7.4
ZABBIXVERSION=	74

.include "${MASTERDIR}/Makefile"
