# $FreeBSD$

MASTERDIR=	${.CURDIR}/../pfSense-pkg-zabbix-proxy

PORTNAME=	pfSense-pkg-zabbix-proxy6

CONFLICTS=	pfSense-pkg-zabbix-proxy \
		pfSense-pkg-zabbix-proxy4 \
		pfSense-pkg-zabbix-proxy44 \
		pfSense-pkg-zabbix-proxy5 \
		pfSense-pkg-zabbix-proxy54

RUN_DEPENDS=	zabbix_proxy:net-mgmt/zabbix6-proxy

ZABBIXINTERNALNAME=	zabbix-proxy6
ZABBIXTITLE=	Zabbix Proxy 6
ZABBIXVERSION=	6

.include "${MASTERDIR}/Makefile"
