# $FreeBSD

MASTERDIR=	${.CURDIR}/../pfSense-pkg-zabbix-agent

PORTNAME=	pfSense-pkg-zabbix-agent44

CONFLICTS=	pfSense-pkg-zabbix-agent \
		pfSense-pkg-zabbix-agent4 \
		pfSense-pkg-zabbix-agent5 \
		pfSense-pkg-zabbix-agent52

RUN_DEPENDS=	zabbix_agentd:net-mgmt/zabbix44-agent

ZABBIXINTERNALNAME=	zabbix-agent44
ZABBIXTITLE=	Zabbix Agent 4.4
ZABBIXVERSION=	44

.include "${MASTERDIR}/Makefile"
