# $FreeBSD$

MASTERDIR=	${.CURDIR}/../pfSense-pkg-zabbix-proxy

PORTNAME=	pfSense-pkg-zabbix-proxy54

CONFLICTS=	pfSense-pkg-zabbix-proxy \
		pfSense-pkg-zabbix-proxy4 \
		pfSense-pkg-zabbix-proxy44 \
		pfSense-pkg-zabbix-proxy5 \
		pfSense-pkg-zabbix-proxy6 \
		pfSense-pkg-zabbix-proxy62

RUN_DEPENDS=	zabbix_proxy:net-mgmt/zabbix54-proxy

ZABBIXINTERNALNAME=	zabbix-proxy54
ZABBIXTITLE=	Zabbix Proxy 5.4
ZABBIXVERSION=	54

.include "${MASTERDIR}/Makefile"
