PORTNAME=	Crypt_CHAP
PORTVERSION=	1.5.0
PORTREVISION=	2
CATEGORIES=	security www pear

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	PEAR class for generating CHAP packets
WWW=		https://pear.php.net/package/Crypt_CHAP

USES=		pear php
USE_PHP=	mcrypt hash

.include <bsd.port.mk>
