<?php

global $priv_list;

$priv_list['page-ios-ipsec-profile-download'] = array();
$priv_list['page-ios-ipsec-profile-download']['name'] = "WebCfg - VPN: iOS IPsec Profile download";
$priv_list['page-ios-ipsec-profile-download']['descr'] = "Allow access to the 'VPN: iOS IPsec Profile download' page.";
$priv_list['page-ios-ipsec-profile-download']['match'] = array();
$priv_list['page-ios-ipsec-profile-download']['match'][] = "vpn_ipsec_profile.php";

?>
