# $FreeBSD$

MASTERDIR=	${.CURDIR}/../pfSense-pkg-zabbix-proxy

PORTNAME=	pfSense-pkg-zabbix-proxy42

CONFLICTS=	pfSense-pkg-zabbix-proxy \
		pfSense-pkg-zabbix-proxy22 \
		pfSense-pkg-zabbix-proxy4

RUN_DEPENDS=	zabbix_proxy:net-mgmt/zabbix42-proxy

ZABBIXINTERNALNAME=	zabbix-proxy42
ZABBIXTITLE=	Zabbix Proxy 4.2
ZABBIXVERSION=	42

.include "${MASTERDIR}/Makefile"
