PORTNAME=	pfSense-ce
DISTVERSION=	${PRODUCT_VERSION}
CATEGORIES=	security

MAINTAINER=	coreteam@pfsense.org
COMMENT?=	pfSense Plus additional package

LICENSE=	APACHE20

RUN_DEPENDS=	drm-515-kmod>0:graphics/drm-515-kmod

DISTFILES=
MASTER_SITES=
NO_BUILD=	yes
NO_WRKSUBDIR=	yes
NO_INSTALL=	yes

.include <bsd.port.post.mk>
