# $FreeBSD$

MASTERDIR=	${.CURDIR}/../pfSense-pkg-zabbix-agent

PORTNAME=	pfSense-pkg-zabbix-agent42

CONFLICTS=	pfSense-pkg-zabbix-agent \
		pfSense-pkg-zabbix-agent4 \
		pfSense-pkg-zabbix-agent44

RUN_DEPENDS=	zabbix_agentd:net-mgmt/zabbix42-agent

ZABBIXINTERNALNAME=	zabbix-agent42
ZABBIXTITLE=	Zabbix Agent 4.2
ZABBIXVERSION=	42

.include "${MASTERDIR}/Makefile"
