# $FreeBSD$

MASTERDIR=	${.CURDIR}/../pfSense-pkg-zabbix-proxy

PORTNAME=	pfSense-pkg-zabbix-proxy52

CONFLICTS=	pfSense-pkg-zabbix-proxy \
		pfSense-pkg-zabbix-proxy4 \
		pfSense-pkg-zabbix-proxy44 \
		pfSense-pkg-zabbix-proxy5

RUN_DEPENDS=	zabbix_proxy:net-mgmt/zabbix52-proxy

ZABBIXINTERNALNAME=	zabbix-proxy52
ZABBIXTITLE=	Zabbix Proxy 5.2
ZABBIXVERSION=	52

.include "${MASTERDIR}/Makefile"
