# $FreeBSD$

MASTERDIR=	${.CURDIR}/../pfSense-pkg-zabbix-proxy

PORTNAME=	pfSense-pkg-zabbix-proxy62

CONFLICTS=
CONFLICTS+=	pfSense-pkg-zabbix-proxy
CONFLICTS+=	pfSense-pkg-zabbix-proxy4
CONFLICTS+=	pfSense-pkg-zabbix-proxy44
CONFLICTS+=	pfSense-pkg-zabbix-proxy5
CONFLICTS+=	pfSense-pkg-zabbix-proxy54
CONFLICTS+=	pfSense-pkg-zabbix-proxy6

RUN_DEPENDS=	zabbix_proxy:net-mgmt/zabbix62-proxy

ZABBIXINTERNALNAME=	zabbix-proxy62
ZABBIXTITLE=	Zabbix Proxy 6.2
ZABBIXVERSION=	62

.include "${MASTERDIR}/Makefile"
