PORTNAME=	appscript
DISTVERSIONPREFIX=	v
DISTVERSION=	0.1.0
CATEGORIES=	archivers

MAINTAINER=	dtxdf@FreeBSD.org
COMMENT=	Very lightweight script to create self-extractable archives

LICENSE=	BSD3CLAUSE
LICENSE_FILE=	${WRKSRC}/LICENSE

USE_GITHUB=	yes
GH_ACCOUNT=	DtxdF

NO_ARCH=	yes
NO_BUILD=	yes

PLIST_FILES=	bin/appscript \
		share/man/man1/appscript.1.gz

.include <bsd.port.mk>
