# $FreeBSD$

MASTERDIR=	${.CURDIR}/../pfSense-pkg-zabbix-proxy

PORTNAME=	pfSense-pkg-zabbix-proxy44

CONFLICTS=	pfSense-pkg-zabbix-proxy \
		pfSense-pkg-zabbix-proxy4 \
		pfSense-pkg-zabbix-proxy5 \
		pfSense-pkg-zabbix-proxy52

RUN_DEPENDS=	zabbix_proxy:net-mgmt/zabbix44-proxy

ZABBIXINTERNALNAME=	zabbix-proxy44
ZABBIXTITLE=	Zabbix Proxy 4.4
ZABBIXVERSION=	44

.include "${MASTERDIR}/Makefile"
