# $FreeBSD

MASTERDIR=	${.CURDIR}/../pfSense-pkg-zabbix-agent

PORTNAME=	pfSense-pkg-zabbix-agent74

CONFLICTS=	pfSense-pkg-zabbix-agent
CONFLICTS+=	pfSense-pkg-zabbix-agent6
CONFLICTS+=	pfSense-pkg-zabbix-agent7

RUN_DEPENDS=	zabbix_agentd:net-mgmt/zabbix74-agent

ZABBIXINTERNALNAME=	zabbix-agent74
ZABBIXTITLE=	Zabbix Agent 7.4
ZABBIXVERSION=	74

.include "${MASTERDIR}/Makefile"
