# $FreeBSD$

PORTNAME=	dpinger
PORTVERSION=	0.0.1.20151205
CATEGORIES=	net

MAINTAINER=	garga@FreeBSD.org
COMMENT=	IP device monitoring tool

LICENSE=	BSD2CLAUSE

USES=		uidfix
USE_GITHUB=	yes
GH_ACCOUNT=	pfsense
GH_PROJECT=	dpinger
GH_TAGNAME=	2ded756e52

PLIST_FILES=	bin/dpinger

.include <bsd.port.mk>
