<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitaba2b16ef20fb2a1401846427e5a3a2a
{
    public static $prefixLengthsPsr4 = array (
        'p' =>
        array (
            'pfSense\\' => 8,
        ),
        'T' =>
        array (
            'Tools\\Rector\\Tests\\' => 19,
            'Tools\\Rector\\' => 13,
        ),
        'N' =>
        array (
            'Netgate\\' => 8,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'pfSense\\' =>
        array (
            0 => '//usr/local/pfSense/include',
        ),
        'Tools\\Rector\\Tests\\' =>
        array (
            0 => __DIR__ . '/../../../../../../..' . '/tools/rector/tests',
        ),
        'Tools\\Rector\\' =>
        array (
            0 => __DIR__ . '/../../../../../../..' . '/tools/rector/src',
        ),
        'Netgate\\' =>
        array (
            0 => '//usr/local/pfSense/include/Netgate',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
        'Tools\\Rector\\Rector\\Rules\\ArrayGetExprRector' => __DIR__ . '/../../../../../../..' . '/tools/rector/src/Rector/Rules/ArrayGetExprRector.php',
        'Tools\\Rector\\Tests\\Rector\\ArrayGetExprRector\\ArrayGetExprRectorTest' => __DIR__ . '/../../../../../../..' . '/tools/rector/tests/Rector/ArrayGetExprRector/ArrayGetExprRectorTest.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitaba2b16ef20fb2a1401846427e5a3a2a::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitaba2b16ef20fb2a1401846427e5a3a2a::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInitaba2b16ef20fb2a1401846427e5a3a2a::$classMap;

        }, null, ClassLoader::class);
    }
}
