<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname(dirname(dirname(dirname(dirname(dirname($vendorDir))))));

return array(
    'pfSense\\' => array('//usr/local/pfSense/include'),
    'Tools\\Rector\\Tests\\' => array($baseDir . '/tools/rector/tests'),
    'Tools\\Rector\\' => array($baseDir . '/tools/rector/src'),
    'Netgate\\' => array('//usr/local/pfSense/include/Netgate'),
);
