<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname(dirname(dirname(dirname(dirname(dirname($vendorDir))))));

return array(
    'pfSense\\' => array('//usr/local/pfSense/include'),
    'mikehaertl\\shellcommand\\' => array($vendorDir . '/mikehaertl/php-shellcommand/src'),
    'Tools\\Rector\\Tests\\' => array($baseDir . '/tools/rector/tests'),
    'Tools\\Rector\\' => array($baseDir . '/tools/rector/src'),
    'Symfony\\Polyfill\\Php80\\' => array($vendorDir . '/symfony/polyfill-php80'),
    'Symfony\\Polyfill\\Php73\\' => array($vendorDir . '/symfony/polyfill-php73'),
    'Symfony\\Contracts\\Service\\' => array($vendorDir . '/symfony/service-contracts'),
    'Symfony\\Contracts\\Cache\\' => array($vendorDir . '/symfony/cache-contracts'),
    'Symfony\\Component\\VarExporter\\' => array($vendorDir . '/symfony/var-exporter'),
    'Symfony\\Component\\Cache\\' => array($vendorDir . '/symfony/cache'),
    'SimplePie\\' => array($vendorDir . '/simplepie/simplepie/src'),
    'Psr\\Log\\' => array($vendorDir . '/psr/log/src'),
    'Psr\\Container\\' => array($vendorDir . '/psr/container/src'),
    'Psr\\Cache\\' => array($vendorDir . '/psr/cache/src'),
    'Netgate\\' => array('//usr/local/pfSense/include/Netgate'),
);
