<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname(dirname(dirname(dirname(dirname(dirname($vendorDir))))));

return array(
    'Composer\\InstalledVersions' => $vendorDir . '/composer/InstalledVersions.php',
    'Tools\\Rector\\Rector\\Rules\\ArrayGetExprRector' => $baseDir . '/tools/rector/src/Rector/Rules/ArrayGetExprRector.php',
    'Tools\\Rector\\Tests\\Rector\\ArrayGetExprRector\\ArrayGetExprRectorTest' => $baseDir . '/tools/rector/tests/Rector/ArrayGetExprRector/ArrayGetExprRectorTest.php',
);
