PORTNAME=	htorrentcreator
DISTVERSION=	0.0.6
CATEGORIES=	net-p2p
MASTER_SITES=	https://github.com/hon4/hTorrentCreatorCLI/releases/download/v${DISTVERSION}/
DISTNAME=	hTorrentCreatorCLI-${DISTVERSION}

MAINTAINER=	greek.team.blog2@gmail.com
COMMENT=	BitTorrent file creator written in C++
WWW=		https://github.com/hon4/hTorrentCreatorCLI

LICENSE=	GPLv2
LICENSE_FILE=	${WRKSRC}/License.txt

.include <bsd.port.mk>
