PORTNAME=	Auth_RADIUS
PORTVERSION=	1.1.0
PORTREVISION=	4
CATEGORIES=	net security pear

MAINTAINER=	bofh@FreeBSD.org
COMMENT=	PEAR wrapper classes for the RADIUS PECL
WWW=		https://pear.php.net/package/Auth_RADIUS

LICENSE=	BSD3CLAUSE

USES=		pear php:flavors
USE_PHP=	radius

.include <bsd.port.mk>
